baseURL: "https://quicksandznzn.github.io/"
title: Focus On Myself
paginate: 10
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-R3QCJGM8T9


minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "quicksandzn - https://github.com/quicksandznzn"
    keywords:
      - 技术
      - Java
      - quicksandzn
      - Spring
      - Spring Cloud
      - Spring Boot
      - Redis
      - Elasticsearch
      - Python
      - Lucene
      - Solr
      - 爬虫
    author: quicksandzn
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: false
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "🏂🏂🏂🏂🏂🏻"
        Content: >
            You Only Live Once！
    socialIcons:
        - name: email
          url: "mailto:quicksandzn@gmail.com"
        - name: instagram
          url: "https://www.instagram.com/quicksandznzn"
        - name: github
          url: "https://github.com/quicksandznzn"

#    editPost:
#        URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#        Text: "Suggest Changes" # edit text
#        appendFilePath: true # to append file path to Edit link



taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    font-size: 11d
    goldmark:
        renderer:
            unsafe: true
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: false
        hl_Lines: ""
        lineAnchors: ""
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        noClasses: true
        style: monokai
        tabWidth: 4

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true